# Generated by Django 5.0.6 on 2024-07-08 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ServerSideApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='studentId',
            new_name='studentID',
        ),
        migrations.RenameField(
            model_name='subjects',
            old_name='subjectId',
            new_name='subjectID',
        ),
    ]
